### PR TITLE
Add Optional Username Argument

### PR DESCRIPTION
**Pull request by AndyM84**
Add an optional username argument to the cluster management script so actions can be performed against users other than the one currently logged in.  Also performed some formatting updates to be yelled at less by my editor.

### CODE REVIEW

**Comment by deweysasser** [comment]
This is actually unnecessary, as current user is only the default filter.  If you were to run with --include otherperson it would filter on otherperson instead.

**Comment by deweysasser** [comment]
Unless you believe that the CLI is more clear with a specific --user flag (instead of just using --include), let's skip this change.

**Comment by deweysasser** [comment]
Also, I highly recommend making reformat changes in a separate commit as it make it much easier to review changes.

**Comment by AndyM84** [comment]
I'm sure we could make the argument that it'd be more clear, but I don't care enough at the moment.

**Pull request closed without merging**
